version: "3.9"
services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    environment:
      - PG_USER=root
      - PG_PASSWORD=123456
      - PG_DB=my_store
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
