version: "3.9"
services:
  # Para Produccion
  # app:
  #   container_name: app
  #   build:
  #     context: .
  #     target: prod
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - PG_USER=root
  #     - PG_PASSWORD=123456
  #     - PG_DB=my_store
  #     - PG_PORT=5432
  #     - PG_HOST=postgres
  #   depends_on:
  #     - postgres

  # Para desarrolllo
  app-dev:
    container_name: app-dev
    # restart: always
    restart: unless-stopped
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    # command: npm run start:dev
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - PG_USER=root
      - PG_PASSWORD=123456
      - PG_DB=my_store
      - PG_PORT=5432
      - PG_HOST=postgres
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  # Base de datos
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # pgadmin web
  postgres-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

volumes:
  postgres-data:
  node_modules:
